# product_data.gd
# Complete supermarket product catalog — data-driven, 100+ products.
# No code changes needed to add/remove products.

class_name ProductData

# Product class is defined in product.gd (class_name Product)
# ProductData methods reference Product globally

static func get_all_products() -> Dictionary:
	return {
		# ── PRODUCE ──────────────────────────────────────────────────────────────
		"apple_red":       Product.new("apple_red",      "Red Apple",      1.50, Color(0.88, 0.22, 0.18), 0, "produce"),
		"apple_green":     Product.new("apple_green",    "Green Apple",   1.80, Color(0.45, 0.78, 0.28), 0, "produce"),
		"banana":          Product.new("banana",          "Banana",         0.80, Color(0.95, 0.85, 0.18), 1, "produce"),
		"orange":          Product.new("orange",          "Orange",         1.20, Color(0.92, 0.52, 0.12), 0, "produce"),
		"lemon":           Product.new("lemon",          "Lemon",          1.00, Color(0.92, 0.90, 0.22), 0, "produce"),
		"grapes":          Product.new("grapes",         "Grapes",         3.50, Color(0.55, 0.28, 0.72), 0, "produce"),
		"grapes_green":    Product.new("grapes_green",   "Green Grapes",   3.80, Color(0.52, 0.82, 0.30), 0, "produce"),
		"strawberry":      Product.new("strawberry",     "Strawberry",     2.20, Color(0.88, 0.22, 0.28), 0, "produce"),
		"blueberry":       Product.new("blueberry",      "Blueberries",    4.00, Color(0.28, 0.28, 0.82), 0, "produce"),
		"watermelon":      Product.new("watermelon",     "Watermelon",     5.50, Color(0.28, 0.68, 0.30), 1, "produce"),
		"pineapple":       Product.new("pineapple",      "Pineapple",      4.50, Color(0.88, 0.78, 0.18), 0, "produce"),
		"mango":           Product.new("mango",           "Mango",          2.80, Color(0.92, 0.68, 0.12), 0, "produce"),
		"peach":           Product.new("peach",          "Peach",          1.80, Color(0.95, 0.68, 0.42), 0, "produce"),
		"pear":            Product.new("pear",           "Pear",           1.50, Color(0.72, 0.85, 0.38), 0, "produce"),
		"cherry":          Product.new("cherry",         "Cherries",       5.00, Color(0.75, 0.12, 0.18), 0, "produce"),
		"kiwi":            Product.new("kiwi",          "Kiwi",           0.80, Color(0.42, 0.62, 0.28), 0, "produce"),
		"carrot":          Product.new("carrot",         "Carrot",         0.90, Color(0.95, 0.52, 0.10), 1, "produce"),
		"broccoli":        Product.new("broccoli",       "Broccoli",       2.20, Color(0.25, 0.58, 0.22), 0, "produce"),
		"tomato":          Product.new("tomato",         "Tomato",         1.50, Color(0.88, 0.22, 0.18), 0, "produce"),
		"lettuce":         Product.new("lettuce",        "Lettuce",        1.80, Color(0.42, 0.78, 0.30), 1, "produce"),
		"cucumber":        Product.new("cucumber",       "Cucumber",       0.90, Color(0.30, 0.65, 0.32), 0, "produce"),
		"onion":           Product.new("onion",          "Onion",          0.70, Color(0.82, 0.72, 0.62), 0, "produce"),
		"garlic":          Product.new("garlic",         "Garlic",         0.50, Color(0.88, 0.85, 0.75), 0, "produce"),
		"potato":          Product.new("potato",         "Potato",         0.60, Color(0.72, 0.55, 0.32), 0, "produce"),
		"sweet_potato":    Product.new("sweet_potato",  "Sweet Potato",   1.20, Color(0.78, 0.42, 0.18), 0, "produce"),
		"mushroom":        Product.new("mushroom",       "Mushroom",       2.50, Color(0.72, 0.58, 0.42), 0, "produce"),
		"bell_pepper_red": Product.new("bell_pepper_red","Red Pepper",    1.80, Color(0.82, 0.18, 0.18), 0, "produce"),
		"bell_pepper_grn": Product.new("bell_pepper_grn","Green Pepper",  1.60, Color(0.22, 0.65, 0.25), 0, "produce"),
		"corn":            Product.new("corn",           "Corn",           0.80, Color(0.92, 0.85, 0.30), 0, "produce"),
		"celery":          Product.new("celery",         "Celery",         1.20, Color(0.58, 0.82, 0.52), 1, "produce"),
		"spinach":         Product.new("spinach",        "Spinach",        2.00, Color(0.22, 0.58, 0.18), 1, "produce"),
		"avocado":         Product.new("avocado",        "Avocado",        1.50, Color(0.42, 0.62, 0.28), 0, "produce"),

		# ── DAIRY ───────────────────────────────────────────────────────────────
		"milk_whole":      Product.new("milk_whole",    "Whole Milk",     3.80, Color(0.94, 0.93, 0.88), 2, "dairy"),
		"milk_skim":       Product.new("milk_skim",     "Skim Milk",     3.50, Color(0.92, 0.92, 0.96), 2, "dairy"),
		"milk_choc":       Product.new("milk_choc",     "Choc Milk",     4.20, Color(0.45, 0.28, 0.18), 2, "dairy"),
		"cream":           Product.new("cream",          "Cream",          2.80, Color(0.95, 0.93, 0.88), 1, "dairy"),
		"butter":          Product.new("butter",         "Butter",         3.50, Color(0.92, 0.86, 0.52), 1, "dairy"),
		"cheese_cheddar":  Product.new("cheese_cheddar","Cheddar",       4.80, Color(0.88, 0.62, 0.18), 1, "dairy"),
		"cheese_mozz":     Product.new("cheese_mozz",   "Mozzarella",     4.50, Color(0.94, 0.93, 0.82), 1, "dairy"),
		"cheese_parmesan": Product.new("cheese_parmesan","Parmesan",     6.50, Color(0.88, 0.82, 0.62), 1, "dairy"),
		"cheese_brie":     Product.new("cheese_brie",   "Brie",           7.20, Color(0.92, 0.88, 0.72), 1, "dairy"),
		"cheese_swiss":    Product.new("cheese_swiss",  "Swiss",          5.50, Color(0.92, 0.82, 0.55), 1, "dairy"),
		"yogurt_straw":    Product.new("yogurt_straw",  "Straw Yogurt",   1.50, Color(0.88, 0.58, 0.65), 4, "dairy"),
		"yogurt_blue":     Product.new("yogurt_blue",   "Blue Yogurt",    1.50, Color(0.38, 0.38, 0.78), 4, "dairy"),
		"yogurt_plain":    Product.new("yogurt_plain",  "Plain Yogurt",   1.20, Color(0.94, 0.93, 0.88), 4, "dairy"),
		"yogurt_greek":    Product.new("yogurt_greek",  "Greek Yogurt",   2.00, Color(0.92, 0.93, 0.88), 4, "dairy"),
		"cottage_cheese":  Product.new("cottage_cheese","Cottage Cheese", 3.20, Color(0.92, 0.90, 0.82), 4, "dairy"),
		"eggs":            Product.new("eggs",           "Eggs (12)",      3.80, Color(0.90, 0.82, 0.65), 1, "dairy"),
		"eggs_free":       Product.new("eggs_free",     "Free Range Eggs", 5.50, Color(0.85, 0.72, 0.55), 1, "dairy"),
		"margarine":       Product.new("margarine",      "Margarine",      2.50, Color(0.90, 0.85, 0.55), 1, "dairy"),
		"halfandhalf":     Product.new("halfandhalf",   "Half & Half",    2.20, Color(0.92, 0.88, 0.78), 2, "dairy"),

		# ── BEVERAGES ───────────────────────────────────────────────────────────
		"cola":            Product.new("cola",           "Cola",           2.00, Color(0.28, 0.22, 0.75), 2, "beverages"),
		"cola_diet":       Product.new("cola_diet",     "Diet Cola",      2.00, Color(0.28, 0.22, 0.75), 2, "beverages"),
		"sprite":          Product.new("sprite",         "Lemon-Lime",     2.00, Color(0.28, 0.82, 0.28), 2, "beverages"),
		"orange_soda":     Product.new("orange_soda",    "Orange Soda",    2.00, Color(0.88, 0.48, 0.12), 2, "beverages"),
		"root_beer":       Product.new("root_beer",     "Root Beer",      2.00, Color(0.52, 0.32, 0.18), 2, "beverages"),
		"grape_soda":      Product.new("grape_soda",    "Grape Soda",     2.00, Color(0.42, 0.18, 0.68), 2, "beverages"),
		"water":           Product.new("water",          "Bottled Water",  0.80, Color(0.58, 0.78, 0.95), 2, "beverages"),
		"sparkling_water": Product.new("sparkling_water","Sparkling H2O", 1.20, Color(0.52, 0.75, 0.92), 2, "beverages"),
		"orange_juice":    Product.new("orange_juice",  "Orange Juice",   3.50, Color(0.92, 0.58, 0.12), 2, "beverages"),
		"apple_juice":     Product.new("apple_juice",   "Apple Juice",    3.00, Color(0.68, 0.82, 0.38), 2, "beverages"),
		"grape_juice":     Product.new("grape_juice",   "Grape Juice",    3.20, Color(0.38, 0.18, 0.62), 2, "beverages"),
		"cranberry_juice": Product.new("cranberry_juice","Cranberry Jc",  3.50, Color(0.62, 0.18, 0.28), 2, "beverages"),
		"tomato_juice":    Product.new("tomato_juice",  "Tomato Juice",   2.80, Color(0.82, 0.18, 0.18), 2, "beverages"),
		"iced_tea":        Product.new("iced_tea",      "Iced Tea",       2.20, Color(0.78, 0.65, 0.42), 2, "beverages"),
		"green_tea":       Product.new("green_tea",    "Green Tea",      2.50, Color(0.32, 0.65, 0.32), 2, "beverages"),
		"coffee":           Product.new("coffee",       "Ground Coffee",  5.50, Color(0.38, 0.25, 0.15), 1, "beverages"),
		"espresso":        Product.new("espresso",      "Espresso Beans", 7.00, Color(0.30, 0.20, 0.12), 1, "beverages"),
		"hot_cocoa":        Product.new("hot_cocoa",    "Hot Cocoa Mix",  3.80, Color(0.42, 0.25, 0.15), 1, "beverages"),
		"almond_milk":     Product.new("almond_milk",  "Almond Milk",    3.50, Color(0.85, 0.78, 0.58), 2, "beverages"),
		"oat_milk":        Product.new("oat_milk",     "Oat Milk",       3.80, Color(0.88, 0.80, 0.52), 2, "beverages"),
		"soy_milk":        Product.new("soy_milk",     "Soy Milk",       3.20, Color(0.88, 0.85, 0.62), 2, "beverages"),
		"energy_drink":    Product.new("energy_drink", "Energy Drink",   3.00, Color(0.28, 0.75, 0.45), 2, "beverages"),
		"sports_drink":    Product.new("sports_drink", "Sports Drink",   2.50, Color(0.22, 0.58, 0.92), 2, "beverages"),
		"beer_lager":      Product.new("beer_lager",   "Lager",          4.50, Color(0.88, 0.72, 0.28), 2, "beverages"),
		"beer_ale":        Product.new("beer_ale",     "Ale",             5.00, Color(0.68, 0.38, 0.18), 2, "beverages"),
		"wine_red":        Product.new("wine_red",     "Red Wine",       8.50, Color(0.52, 0.12, 0.18), 2, "beverages"),
		"wine_white":      Product.new("wine_white",   "White Wine",     7.50, Color(0.88, 0.85, 0.52), 2, "beverages"),

		# ── SNACKS ─────────────────────────────────────────────────────────────
		"chips_plain":     Product.new("chips_plain",   "Plain Chips",    2.80, Color(0.92, 0.75, 0.28), 1, "snacks"),
		"chips_bbq":       Product.new("chips_bbq",    "BBQ Chips",      2.80, Color(0.78, 0.38, 0.18), 1, "snacks"),
		"chips_sourcream": Product.new("chips_sourcream","Sour Cream",   2.80, Color(0.88, 0.82, 0.62), 1, "snacks"),
		"chips_cheddar":   Product.new("chips_cheddar", "Cheddar Chips",  2.80, Color(0.88, 0.55, 0.12), 1, "snacks"),
		"chips_tortilla":  Product.new("chips_tortilla","Tortilla Chips", 2.50, Color(0.85, 0.72, 0.35), 1, "snacks"),
		"chips_potato":    Product.new("chips_potato", "Potato Chips",    2.50, Color(0.95, 0.82, 0.42), 1, "snacks"),
		"popcorn":         Product.new("popcorn",       "Popcorn",        2.20, Color(0.92, 0.85, 0.42), 1, "snacks"),
		"pretzels":        Product.new("pretzels",      "Pretzels",       2.50, Color(0.72, 0.52, 0.28), 1, "snacks"),
		"nuts_mixed":      Product.new("nuts_mixed",    "Mixed Nuts",     5.50, Color(0.62, 0.45, 0.25), 0, "snacks"),
		"nuts_peanut":     Product.new("nuts_peanut",   "Peanuts",        3.80, Color(0.72, 0.48, 0.22), 0, "snacks"),
		"nuts_almond":     Product.new("nuts_almond",   "Almonds",        6.00, Color(0.65, 0.48, 0.28), 0, "snacks"),
		"trail_mix":       Product.new("trail_mix",    "Trail Mix",      4.50, Color(0.62, 0.42, 0.22), 0, "snacks"),
		"cookies_choc":    Product.new("cookies_choc",  "Choc Cookies",   3.20, Color(0.42, 0.28, 0.18), 1, "snacks"),
		"cookies_sugar":   Product.new("cookies_sugar","Sugar Cookies",   3.00, Color(0.92, 0.78, 0.55), 1, "snacks"),
		"cookies_oreo":    Product.new("cookies_oreo",  "Oreo",           3.50, Color(0.18, 0.18, 0.22), 1, "snacks"),
		"cookies_graham":   Product.new("cookies_graham","Graham Crackers",2.80, Color(0.72, 0.55, 0.32), 1, "snacks"),
		"candy_chocbar":   Product.new("candy_chocbar", "Choc Bar",       1.50, Color(0.42, 0.25, 0.15), 1, "snacks"),
		"candy_gummy":     Product.new("candy_gummy",   "Gummy Bears",    1.20, Color(0.88, 0.28, 0.38), 0, "snacks"),
		"candy_lollipop":  Product.new("candy_lollipop","Lollipop",        0.80, Color(0.92, 0.28, 0.52), 0, "snacks"),
		"candy_mints":     Product.new("candy_mints",   "Mints",          1.00, Color(0.85, 0.92, 0.88), 0, "snacks"),
		"marshmallow":     Product.new("marshmallow",  "Marshmallows",    2.20, Color(0.92, 0.92, 0.92), 0, "snacks"),
		"chocolate_dark":  Product.new("chocolate_dark","Dark Chocolate",  3.50, Color(0.28, 0.15, 0.10), 1, "snacks"),
		"chocolate_milk":  Product.new("chocolate_milk","Milk Choc",      2.80, Color(0.48, 0.30, 0.18), 1, "snacks"),
		"chocolate_white": Product.new("chocolate_white","White Choc",    3.00, Color(0.92, 0.88, 0.72), 1, "snacks"),

		# ── MEAT ────────────────────────────────────────────────────────────────
		"beef_steak":      Product.new("beef_steak",   "Beef Steak",    12.00, Color(0.65, 0.22, 0.18), 1, "meat"),
		"beef_ground":     Product.new("beef_ground",   "Ground Beef",    7.50, Color(0.62, 0.22, 0.18), 1, "meat"),
		"beef_roast":      Product.new("beef_roast",   "Beef Roast",     10.00, Color(0.58, 0.22, 0.18), 1, "meat"),
		"beef_shortribs":  Product.new("beef_shortribs","Short Ribs",   9.00, Color(0.62, 0.25, 0.18), 1, "meat"),
		"beef_liver":      Product.new("beef_liver",   "Beef Liver",     5.00, Color(0.62, 0.28, 0.32), 1, "meat"),
		"chicken_breast":  Product.new("chicken_breast","Chicken Breast", 7.50, Color(0.88, 0.72, 0.55), 1, "meat"),
		"chicken_thigh":   Product.new("chicken_thigh", "Chicken Thigh",  5.50, Color(0.85, 0.58, 0.38), 1, "meat"),
		"chicken_wings":   Product.new("chicken_wings","Chicken Wings",   8.00, Color(0.88, 0.62, 0.38), 0, "meat"),
		"chicken_drum":    Product.new("chicken_drum", "Drumstick",      5.00, Color(0.82, 0.62, 0.42), 0, "meat"),
		"turkey_breast":   Product.new("turkey_breast","Turkey Breast",   9.50, Color(0.82, 0.68, 0.52), 1, "meat"),
		"pork_chop":       Product.new("pork_chop",    "Pork Chops",     8.00, Color(0.78, 0.52, 0.55), 1, "meat"),
		"pork_ribs":       Product.new("pork_ribs",    "Pork Ribs",      9.50, Color(0.75, 0.45, 0.48), 1, "meat"),
		"pork_roast":      Product.new("pork_roast",   "Pork Roast",     8.50, Color(0.78, 0.52, 0.52), 1, "meat"),
		"bacon":           Product.new("bacon",         "Bacon",          6.50, Color(0.82, 0.32, 0.25), 1, "meat"),
		"ham":             Product.new("ham",           "Ham",             7.00, Color(0.88, 0.55, 0.52), 1, "meat"),
		"sausage_pork":    Product.new("sausage_pork", "Pork Sausage",   5.50, Color(0.72, 0.35, 0.28), 0, "meat"),
		"sausage_brat":    Product.new("sausage_brat", "Bratwurst",      6.00, Color(0.68, 0.38, 0.32), 0, "meat"),
		"hotdog":          Product.new("hotdog",        "Hot Dogs",        4.00, Color(0.88, 0.55, 0.45), 0, "meat"),
		"lamb_chop":       Product.new("lamb_chop",   "Lamb Chops",    13.00, Color(0.62, 0.25, 0.28), 1, "meat"),
		"fish_salmon":     Product.new("fish_salmon",  "Salmon",         12.00, Color(0.78, 0.42, 0.38), 1, "meat"),
		"fish_tuna":       Product.new("fish_tuna",    "Tuna Steak",    14.00, Color(0.62, 0.38, 0.42), 1, "meat"),
		"fish_cod":        Product.new("fish_cod",     "Cod Fillet",     9.00, Color(0.72, 0.68, 0.62), 1, "meat"),
		"shrimp":          Product.new("shrimp",        "Shrimp",        12.00, Color(0.88, 0.52, 0.45), 0, "meat"),
		"crab":            Product.new("crab",          "Crab Meat",     15.00, Color(0.82, 0.45, 0.28), 1, "meat"),

		# ── DELI ───────────────────────────────────────────────────────────────
		"deli_turkey":     Product.new("deli_turkey",   "Deli Turkey",    8.50, Color(0.88, 0.72, 0.58), 1, "deli"),
		"deli_ham":        Product.new("deli_ham",      "Deli Ham",       7.50, Color(0.90, 0.62, 0.55), 1, "deli"),
		"deli_roastbeef":  Product.new("deli_roastbeef","Roast Beef",   9.00, Color(0.62, 0.28, 0.22), 1, "deli"),
		"deli_salami":     Product.new("deli_salami",   "Salami",         7.50, Color(0.82, 0.38, 0.32), 1, "deli"),
		"deli_bologna":    Product.new("deli_bologna", "Bologna",        5.50, Color(0.88, 0.62, 0.62), 1, "deli"),
		"deli_chiicken":   Product.new("deli_chiicken","Chicken Salad",  6.50, Color(0.90, 0.78, 0.55), 4, "deli"),
		"deli_egg":        Product.new("deli_egg",      "Egg Salad",      5.50, Color(0.92, 0.85, 0.58), 4, "deli"),
		"deli_coleslaw":    Product.new("deli_coleslaw","Coleslaw",      3.50, Color(0.88, 0.88, 0.52), 4, "deli"),
		"deli_potatosalad":Product.new("deli_potatosalad","Potato Salad",3.80, Color(0.88, 0.82, 0.52), 4, "deli"),
		"deli_macaroni":   Product.new("deli_macaroni", "Macaroni Salad", 3.80, Color(0.92, 0.82, 0.48), 4, "deli"),
		"deli_hummus":     Product.new("deli_hummus",  "Hummus",         4.00, Color(0.78, 0.68, 0.42), 4, "deli"),

		# ── BAKERY ────────────────────────────────────────────────────────────
		"bread_white":     Product.new("bread_white",   "White Bread",    2.80, Color(0.88, 0.72, 0.48), 1, "bakery"),
		"bread_wheat":     Product.new("bread_wheat",   "Wheat Bread",   3.20, Color(0.62, 0.42, 0.22), 1, "bakery"),
		"bread_sourdough": Product.new("bread_sourdough","Sourdough",     3.80, Color(0.82, 0.62, 0.35), 1, "bakery"),
		"bread_rye":       Product.new("bread_rye",     "Rye Bread",     3.50, Color(0.58, 0.38, 0.22), 1, "bakery"),
		"bread_baguette":  Product.new("bread_baguette","Baguette",       2.50, Color(0.88, 0.75, 0.52), 1, "bakery"),
		"bread_brioche":   Product.new("bread_brioche", "Brioche",       4.00, Color(0.92, 0.72, 0.42), 1, "bakery"),
		"bread_pumpernickel":Product.new("bread_pumpernickel","Pumpernickel",3.50, Color(0.38, 0.25, 0.15), 1, "bakery"),
		"bagel":           Product.new("bagel",         "Bagel",          0.80, Color(0.75, 0.58, 0.38), 0, "bakery"),
		"croissant":       Product.new("croissant",     "Croissant",      1.50, Color(0.88, 0.70, 0.42), 1, "bakery"),
		"muffin_blue":     Product.new("muffin_blue",  "Blueberry Muffin",1.80, Color(0.32, 0.28, 0.58), 0, "bakery"),
		"muffin_choc":     Product.new("muffin_choc",  "Choc Muffin",    1.80, Color(0.32, 0.22, 0.15), 0, "bakery"),
		"donut_glazed":    Product.new("donut_glazed", "Glazed Donut",   1.20, Color(0.88, 0.68, 0.42), 0, "bakery"),
		"donut_choc":      Product.new("donut_choc",   "Choc Donut",     1.20, Color(0.42, 0.28, 0.18), 0, "bakery"),
		"cake_choc":       Product.new("cake_choc",    "Choc Cake",      15.00, Color(0.32, 0.20, 0.12), 3, "bakery"),
		"cake_vanilla":    Product.new("cake_vanilla", "Vanilla Cake",   14.00, Color(0.92, 0.88, 0.72), 3, "bakery"),
		"cake_cheesecake": Product.new("cake_cheesecake","Cheesecake",   18.00, Color(0.92, 0.88, 0.62), 3, "bakery"),
		"pie_apple":       Product.new("pie_apple",    "Apple Pie",      10.00, Color(0.72, 0.48, 0.28), 3, "bakery"),
		"pie_cherry":      Product.new("pie_cherry",   "Cherry Pie",     10.00, Color(0.62, 0.18, 0.22), 3, "bakery"),
		"pastry":          Product.new("pastry",        "Danish Pastry",  2.00, Color(0.88, 0.72, 0.48), 1, "bakery"),
		"tortilla":        Product.new("tortilla",      "Tortilla Wrap",  2.20, Color(0.85, 0.78, 0.58), 1, "bakery"),
		"naan":            Product.new("naan",          "Naan Bread",     2.50, Color(0.88, 0.72, 0.48), 1, "bakery"),

		# ── PANTRY ─────────────────────────────────────────────────────────────
		"rice_white":      Product.new("rice_white",    "White Rice",     3.00, Color(0.88, 0.85, 0.68), 1, "pantry"),
		"rice_brown":      Product.new("rice_brown",    "Brown Rice",     3.50, Color(0.58, 0.42, 0.25), 1, "pantry"),
		"rice_basmathi":   Product.new("rice_basmathi","Basmathi Rice", 4.50, Color(0.88, 0.82, 0.62), 1, "pantry"),
		"pasta_spaghetti": Product.new("pasta_spaghetti","Spaghetti",     1.80, Color(0.88, 0.80, 0.55), 1, "pantry"),
		"pasta_penne":     Product.new("pasta_penne",  "Penne",          1.80, Color(0.88, 0.80, 0.55), 1, "pantry"),
		"pasta_fusilli":   Product.new("pasta_fusilli","Fusilli",       1.80, Color(0.88, 0.80, 0.55), 1, "pantry"),
		"pasta_lasagna":   Product.new("pasta_lasagna","Lasagna Sheets",2.20, Color(0.88, 0.82, 0.58), 1, "pantry"),
		"pasta_ramen":     Product.new("pasta_ramen",  "Ramen Noodles",  0.50, Color(0.85, 0.75, 0.45), 1, "pantry"),
		"flour_allpur":    Product.new("flour_allpur", "All-Purpose Fl", 2.50, Color(0.90, 0.88, 0.82), 1, "pantry"),
		"flour_bread":     Product.new("flour_bread",  "Bread Flour",    2.80, Color(0.88, 0.82, 0.68), 1, "pantry"),
		"flour_almond":    Product.new("flour_almond", "Almond Flour",   8.00, Color(0.72, 0.58, 0.42), 1, "pantry"),
		"sugar_white":     Product.new("sugar_white",  "White Sugar",     2.20, Color(0.92, 0.92, 0.88), 1, "pantry"),
		"sugar_brown":     Product.new("sugar_brown",  "Brown Sugar",     2.50, Color(0.62, 0.42, 0.22), 1, "pantry"),
		"sugar_powder":    Product.new("sugar_powder", "Powdered Sugar", 2.80, Color(0.92, 0.92, 0.88), 1, "pantry"),
		"honey":           Product.new("honey",         "Honey",          5.50, Color(0.88, 0.68, 0.18), 2, "pantry"),
		"maple_syrup":     Product.new("maple_syrup",  "Maple Syrup",    7.00, Color(0.72, 0.48, 0.18), 2, "pantry"),
		"jam_strawberry":  Product.new("jam_strawberry","Strawberry Jam", 3.50, Color(0.82, 0.18, 0.22), 2, "pantry"),
		"jam_grape":       Product.new("jam_grape",     "Grape Jelly",    3.20, Color(0.42, 0.18, 0.62), 2, "pantry"),
		"peanut_butter":   Product.new("peanut_butter","Peanut Butter",  3.80, Color(0.72, 0.48, 0.22), 2, "pantry"),
		"olive_oil":       Product.new("olive_oil",     "Olive Oil",      6.50, Color(0.52, 0.72, 0.32), 2, "pantry"),
		"cooking_oil":     Product.new("cooking_oil",  "Vegetable Oil",  3.20, Color(0.72, 0.68, 0.28), 2, "pantry"),
		"coconut_oil":     Product.new("coconut_oil",  "Coconut Oil",    5.50, Color(0.88, 0.85, 0.58), 2, "pantry"),
		"vinegar_white":   Product.new("vinegar_white","White Vinegar",  1.50, Color(0.88, 0.88, 0.82), 2, "pantry"),
		"vinegar_balsamic":Product.new("vinegar_balsamic","Balsamic",   5.00, Color(0.28, 0.18, 0.12), 2, "pantry"),
		"soy_sauce":       Product.new("soy_sauce",     "Soy Sauce",      2.80, Color(0.28, 0.18, 0.10), 2, "pantry"),
		"ketchup":         Product.new("ketchup",       "Ketchup",        2.50, Color(0.82, 0.12, 0.12), 2, "pantry"),
		"mustard":         Product.new("mustard",       "Mustard",        2.20, Color(0.92, 0.82, 0.28), 2, "pantry"),
		"mayonnaise":      Product.new("mayonnaise",    "Mayonnaise",     3.50, Color(0.92, 0.90, 0.78), 2, "pantry"),
		"bbq_sauce":      Product.new("bbq_sauce",    "BBQ Sauce",      3.20, Color(0.42, 0.22, 0.12), 2, "pantry"),
		"hot_sauce":       Product.new("hot_sauce",     "Hot Sauce",      3.00, Color(0.78, 0.12, 0.12), 2, "pantry"),
		"salsa":           Product.new("salsa",         "Salsa",          3.00, Color(0.82, 0.18, 0.18), 2, "pantry"),
		"pasta_sauce_red": Product.new("pasta_sauce_red","Red Sauce",    3.50, Color(0.82, 0.18, 0.12), 2, "pantry"),
		"pasta_sauce_white":Product.new("pasta_sauce_white","White Sauce",3.50, Color(0.92, 0.88, 0.72), 2, "pantry"),
		"broth_beef":      Product.new("broth_beef",   "Beef Broth",     2.50, Color(0.52, 0.32, 0.22), 2, "pantry"),
		"broth_chicken":   Product.new("broth_chicken","Chicken Broth",  2.20, Color(0.85, 0.72, 0.42), 2, "pantry"),
		"broth_veg":       Product.new("broth_veg",    "Vegetable Broth",2.50, Color(0.42, 0.58, 0.28), 2, "pantry"),
		"soup_chicken":    Product.new("soup_chicken", "Chicken Noodle", 1.80, Color(0.85, 0.72, 0.45), 2, "pantry"),
		"soup_tomato":     Product.new("soup_tomato",  "Tomato Soup",    1.80, Color(0.82, 0.18, 0.18), 2, "pantry"),
		"soup_veg":        Product.new("soup_veg",     "Vegetable Soup", 1.80, Color(0.42, 0.58, 0.28), 2, "pantry"),
		"soup_mushroom":   Product.new("soup_mushroom","Mushroom Soup",  1.80, Color(0.65, 0.48, 0.35), 2, "pantry"),
		"beans_kidney":    Product.new("beans_kidney", "Kidney Beans",   1.20, Color(0.62, 0.18, 0.18), 1, "pantry"),
		"beans_black":      Product.new("beans_black",  "Black Beans",    1.20, Color(0.22, 0.18, 0.15), 1, "pantry"),
		"beans_chickpeas": Product.new("beans_chickpeas","Chickpeas",    1.50, Color(0.72, 0.58, 0.38), 1, "pantry"),
		"lentils":         Product.new("lentils",      "Lentils",        1.80, Color(0.72, 0.48, 0.28), 1, "pantry"),
		"cereal_corn":     Product.new("cereal_corn",  "Corn Flakes",    3.80, Color(0.92, 0.85, 0.38), 1, "pantry"),
		"cereal_oat":      Product.new("cereal_oat",   "Oatmeal",        3.50, Color(0.65, 0.48, 0.28), 1, "pantry"),
		"cereal_granola":  Product.new("cereal_granola","Granola",       4.80, Color(0.62, 0.45, 0.25), 1, "pantry"),
		"cereal_muesli":   Product.new("cereal_muesli","Muesli",         4.50, Color(0.58, 0.42, 0.25), 1, "pantry"),
		"cereal_choc":     Product.new("cereal_choc",  "Choc cereal",    4.20, Color(0.42, 0.25, 0.15), 1, "pantry"),
		"instant_oatmeal": Product.new("instant_oatmeal","Instant Oat",   3.00, Color(0.65, 0.48, 0.28), 1, "pantry"),
		"pancake_mix":     Product.new("pancake_mix", "Pancake Mix",    3.20, Color(0.88, 0.82, 0.62), 1, "pantry"),
		"baking_powder":   Product.new("baking_powder","Baking Powder",  2.50, Color(0.88, 0.88, 0.82), 1, "pantry"),
		"baking_soda":     Product.new("baking_soda",  "Baking Soda",    1.50, Color(0.88, 0.88, 0.85), 1, "pantry"),
		"yeast":           Product.new("yeast",         "Yeast",          2.80, Color(0.82, 0.72, 0.48), 1, "pantry"),
		"corn_starch":     Product.new("corn_starch",  "Corn Starch",    2.20, Color(0.90, 0.88, 0.82), 1, "pantry"),
		"cocoa_powder":    Product.new("cocoa_powder", "Cocoa Powder",   3.50, Color(0.32, 0.20, 0.12), 1, "pantry"),
		"vanilla_extract": Product.new("vanilla_extract","Vanilla",      4.50, Color(0.68, 0.58, 0.38), 2, "pantry"),
		"chicken_season":  Product.new("chicken_season","Chicken Season",2.50, Color(0.85, 0.65, 0.35), 1, "pantry"),
		"italian_season":  Product.new("italian_season","Italian Season",2.50, Color(0.38, 0.52, 0.22), 1, "pantry"),
		"paprika":         Product.new("paprika",      "Paprika",        2.20, Color(0.82, 0.28, 0.12), 1, "pantry"),
		"cinnamon":        Product.new("cinnamon",     "Cinnamon",        3.00, Color(0.62, 0.38, 0.22), 1, "pantry"),
		"garlic_salt":     Product.new("garlic_salt",  "Garlic Salt",    2.20, Color(0.88, 0.82, 0.72), 1, "pantry"),
		"black_pepper":    Product.new("black_pepper","Black Pepper",   2.80, Color(0.22, 0.18, 0.15), 1, "pantry"),
		"sea_salt":        Product.new("sea_salt",     "Sea Salt",       2.50, Color(0.85, 0.88, 0.88), 1, "pantry"),
		"sugar_confectioner":Product.new("sugar_confectioner","Powdered Sugar",2.80, Color(0.92, 0.92, 0.88), 1, "pantry"),

		# ── FROZEN ────────────────────────────────────────────────────────────
		"frozen_pizza":     Product.new("frozen_pizza",  "Frozen Pizza",   6.50, Color(0.82, 0.22, 0.18), 3, "frozen"),
		"frozen_burger":    Product.new("frozen_burger", "Burger Patties", 5.50, Color(0.62, 0.32, 0.22), 3, "frozen"),
		"frozen_fish":      Product.new("frozen_fish",   "Fish Sticks",    5.00, Color(0.78, 0.62, 0.48), 1, "frozen"),
		"frozen_chicken":   Product.new("frozen_chicken","Chicken Nuggets",5.00, Color(0.88, 0.68, 0.42), 1, "frozen"),
		"frozen_fries":     Product.new("frozen_fries",  "Frozen Fries",   3.20, Color(0.88, 0.78, 0.48), 1, "frozen"),
		"frozen_corn":      Product.new("frozen_corn",   "Frozen Corn",    2.20, Color(0.92, 0.85, 0.42), 1, "frozen"),
		"frozen_broccoli":  Product.new("frozen_broccoli","Frozen Brocc", 2.50, Color(0.28, 0.62, 0.25), 1, "frozen"),
		"frozen_mixveg":    Product.new("frozen_mixveg","Mixed Veg",      2.50, Color(0.42, 0.58, 0.28), 1, "frozen"),
		"frozen_peas":      Product.new("frozen_peas",   "Frozen Peas",    2.20, Color(0.28, 0.58, 0.28), 0, "frozen"),
		"icecream_vanilla": Product.new("icecream_vanilla","Vanilla Ice",  4.50, Color(0.92, 0.88, 0.72), 4, "frozen"),
		"icecream_choc":    Product.new("icecream_choc", "Choc Ice Cream", 4.50, Color(0.32, 0.20, 0.12), 4, "frozen"),
		"icecream_straw":   Product.new("icecream_straw","Straw Ice Cream",4.50, Color(0.88, 0.42, 0.55), 4, "frozen"),
		"icecream_mint":    Product.new("icecream_mint", "Mint Ice Cream", 4.50, Color(0.42, 0.78, 0.52), 4, "frozen"),
		"frozen_waffles":   Product.new("frozen_waffles","Waffles",       3.20, Color(0.88, 0.75, 0.45), 1, "frozen"),
		"frozen_tv_dinner": Product.new("frozen_tv_dinner","TV Dinner",   4.00, Color(0.72, 0.55, 0.32), 3, "frozen"),
		"frozen_taquitos":  Product.new("frozen_taquitos","Taquitos",     4.50, Color(0.85, 0.72, 0.38), 1, "frozen"),
		"popsicle":         Product.new("popsicle",      "Popsicle",       1.50, Color(0.88, 0.28, 0.38), 0, "frozen"),

		# ── HEALTH & BEAUTY ───────────────────────────────────────────────────
		"vitamins_mult":    Product.new("vitamins_mult","Multi-Vitamins", 8.50, Color(0.82, 0.28, 0.28), 1, "hbc"),
		"vitamins_c":       Product.new("vitamins_c",   "Vitamin C",       6.50, Color(0.88, 0.58, 0.28), 1, "hbc"),
		"vitamins_d":       Product.new("vitamins_d",   "Vitamin D",       6.50, Color(0.88, 0.82, 0.42), 1, "hbc"),
		"vitamins_b":       Product.new("vitamins_b",   "Vitamin B",       6.50, Color(0.78, 0.55, 0.28), 1, "hbc"),
		"fish_oil":        Product.new("fish_oil",     "Fish Oil",        7.50, Color(0.28, 0.38, 0.65), 2, "hbc"),
		"calcium":          Product.new("calcium",       "Calcium",        5.50, Color(0.88, 0.88, 0.82), 1, "hbc"),
		"iron_supplement":  Product.new("iron_supplement","Iron",          5.00, Color(0.62, 0.18, 0.18), 1, "hbc"),
		"pain_reliever":   Product.new("pain_reliever","Pain Relief",    5.50, Color(0.28, 0.38, 0.78), 1, "hbc"),
		"cough_syrup":      Product.new("cough_syrup",  "Cough Syrup",    6.00, Color(0.62, 0.38, 0.38), 2, "hbc"),
		"cold_medicine":    Product.new("cold_medicine", "Cold Medicine",  6.50, Color(0.28, 0.62, 0.78), 2, "hbc"),
		"allergy_med":      Product.new("allergy_med",   "Allergy Med",    7.00, Color(0.28, 0.68, 0.42), 1, "hbc"),
		"antacid":          Product.new("antacid",       "Antacid",        4.50, Color(0.82, 0.82, 0.72), 1, "hbc"),
		"toothpaste":       Product.new("toothpaste",    "Toothpaste",     3.50, Color(0.82, 0.88, 0.92), 1, "hbc"),
		"mouthwash":        Product.new("mouthwash",      "Mouthwash",      4.00, Color(0.28, 0.78, 0.65), 2, "hbc"),
		"shampoo":          Product.new("shampoo",       "Shampoo",        4.50, Color(0.28, 0.62, 0.82), 2, "hbc"),
		"conditioner":      Product.new("conditioner",   "Conditioner",     4.50, Color(0.82, 0.68, 0.82), 2, "hbc"),
		"body_wash":        Product.new("body_wash",     "Body Wash",      4.00, Color(0.28, 0.55, 0.75), 2, "hbc"),
		"hand_soap":        Product.new("hand_soap",     "Hand Soap",      2.50, Color(0.82, 0.82, 0.72), 2, "hbc"),
		"deodorant":        Product.new("deodorant",     "Deodorant",      4.50, Color(0.28, 0.38, 0.68), 2, "hbc"),
		"razor":            Product.new("razor",         "Razors",         5.00, Color(0.52, 0.58, 0.68), 1, "hbc"),
		"bandages":         Product.new("bandages",      "Bandages",       3.50, Color(0.88, 0.82, 0.72), 1, "hbc"),
		"sunscreen":        Product.new("sunscreen",     "Sunscreen",      6.50, Color(0.28, 0.68, 0.92), 2, "hbc"),
		"lip_balm":         Product.new("lip_balm",      "Lip Balm",       2.00, Color(0.82, 0.52, 0.52), 0, "hbc"),
		"hand_cream":       Product.new("hand_cream",    "Hand Cream",     3.50, Color(0.88, 0.78, 0.68), 2, "hbc"),
		"contact_lens":     Product.new("contact_lens",  "Contact Lens",   12.00, Color(0.28, 0.52, 0.78), 1, "hbc"),

		# ── HOUSEHOLD ─────────────────────────────────────────────────────────
		"paper_towels":    Product.new("paper_towels",  "Paper Towels",   3.50, Color(0.88, 0.88, 0.82), 1, "household"),
		"toilet_paper":    Product.new("toilet_paper",  "Toilet Paper",   4.50, Color(0.92, 0.92, 0.88), 1, "household"),
		"tissues":         Product.new("tissues",       "Tissues",        2.00, Color(0.88, 0.85, 0.78), 1, "household"),
		"dish_soap":       Product.new("dish_soap",     "Dish Soap",      2.80, Color(0.28, 0.68, 0.88), 2, "household"),
		"laundry_det":     Product.new("laundry_det",  "Laundry Det",   6.50, Color(0.28, 0.42, 0.78), 2, "household"),
		"fabric_softener": Product.new("fabric_softener","Fabric Soft",  4.00, Color(0.68, 0.28, 0.68), 2, "household"),
		"bleach":          Product.new("bleach",         "Bleach",        3.50, Color(0.88, 0.88, 0.92), 2, "household"),
		"all_purpose_cleaner":Product.new("all_purpose_cleaner","All-Purpose", 3.20, Color(0.28, 0.82, 0.42), 2, "household"),
		"glass_cleaner":   Product.new("glass_cleaner", "Glass Cleaner",  3.00, Color(0.58, 0.82, 0.95), 2, "household"),
		"trash_bags":      Product.new("trash_bags",    "Trash Bags",     5.00, Color(0.22, 0.22, 0.25), 1, "household"),
		"aluminum_foil":   Product.new("aluminum_foil", "Aluminum Foil",  3.20, Color(0.72, 0.72, 0.75), 1, "household"),
		"plastic_wrap":    Product.new("plastic_wrap",  "Plastic Wrap",   2.50, Color(0.82, 0.88, 0.92), 1, "household"),
		"ziplock_bags":    Product.new("ziplock_bags", "Ziplock Bags",   3.80, Color(0.82, 0.88, 0.92), 1, "household"),
		"sponge":          Product.new("sponge",         "Sponge",         1.50, Color(0.92, 0.85, 0.32), 1, "household"),
		"light_bulb":      Product.new("light_bulb",    "Light Bulb",     2.50, Color(0.92, 0.92, 0.78), 0, "household"),
		"batteries_aa":    Product.new("batteries_aa",  "Batteries AA",   5.50, Color(0.28, 0.28, 0.35), 1, "household"),
		"batteries_aaa":   Product.new("batteries_aaa", "Batteries AAA",  5.00, Color(0.28, 0.28, 0.35), 1, "household"),
		"candle":          Product.new("candle",         "Candle",         4.00, Color(0.78, 0.55, 0.22), 0, "household"),
		"insect_spray":    Product.new("insect_spray",  "Insect Spray",   5.00, Color(0.42, 0.65, 0.22), 2, "household"),

		# ── BABY ───────────────────────────────────────────────────────────────
		"diapers":          Product.new("diapers",        "Diapers",       15.00, Color(0.82, 0.88, 0.78), 1, "baby"),
		"baby_wipes":       Product.new("baby_wipes",    "Baby Wipes",     4.00, Color(0.82, 0.88, 0.82), 1, "baby"),
		"baby_formula":     Product.new("baby_formula",  "Baby Formula",   12.00, Color(0.28, 0.45, 0.82), 2, "baby"),
		"baby_food":        Product.new("baby_food",     "Baby Food",      0.80, Color(0.88, 0.68, 0.42), 1, "baby"),
		"baby_shampoo":     Product.new("baby_shampoo",  "Baby Shampoo",   4.50, Color(0.82, 0.92, 0.88), 2, "baby"),
		"baby_lotion":      Product.new("baby_lotion",   "Baby Lotion",    4.00, Color(0.88, 0.82, 0.72), 2, "baby"),
		"baby_oil":         Product.new("baby_oil",      "Baby Oil",       3.50, Color(0.82, 0.92, 0.78), 2, "baby"),
		"diaper_cream":    Product.new("diaper_cream",  "Diaper Cream",   4.50, Color(0.88, 0.72, 0.55), 2, "baby"),
		"pacifier":         Product.new("pacifier",      "Pacifier",       3.00, Color(0.82, 0.88, 0.92), 0, "baby"),
		"baby_bottle":      Product.new("baby_bottle",   "Baby Bottle",    5.00, Color(0.58, 0.82, 0.95), 2, "baby"),
	}

static func get_aisle_products(aisle_id: String) -> Array:
	var all := get_all_products()
	var mapping := {
		"aisle_produce":  ["apple_red","apple_green","banana","orange","lemon","grapes","grapes_green","strawberry","blueberry","watermelon","pineapple","mango","peach","pear","cherry","kiwi","carrot","broccoli","tomato","lettuce","cucumber","onion","garlic","potato","sweet_potato","mushroom","bell_pepper_red","bell_pepper_grn","corn","celery","spinach","avocado"],
		"aisle_dairy":    ["milk_whole","milk_skim","milk_choc","cream","butter","cheese_cheddar","cheese_mozz","cheese_parmesan","cheese_brie","cheese_swiss","yogurt_straw","yogurt_blue","yogurt_plain","yogurt_greek","cottage_cheese","eggs","eggs_free","margarine","halfandhalf"],
		"aisle_drinks":   ["cola","cola_diet","sprite","orange_soda","root_beer","grape_soda","water","sparkling_water","orange_juice","apple_juice","grape_juice","cranberry_juice","tomato_juice","iced_tea","green_tea","coffee","espresso","hot_cocoa","almond_milk","oat_milk","soy_milk","energy_drink","sports_drink","beer_lager","beer_ale","wine_red","wine_white"],
		"aisle_snacks":   ["chips_plain","chips_bbq","chips_sourcream","chips_cheddar","chips_tortilla","chips_potato","popcorn","pretzels","nuts_mixed","nuts_peanut","nuts_almond","trail_mix","cookies_choc","cookies_sugar","cookies_oreo","cookies_graham","candy_chocbar","candy_gummy","candy_lollipop","candy_mints","marshmallow","chocolate_dark","chocolate_milk","chocolate_white"],
		"aisle_meat":     ["beef_steak","beef_ground","beef_roast","beef_shortribs","beef_liver","chicken_breast","chicken_thigh","chicken_wings","chicken_drum","turkey_breast","pork_chop","pork_ribs","pork_roast","bacon","ham","sausage_pork","sausage_brat","hotdog","lamb_chop","fish_salmon","fish_tuna","fish_cod","shrimp","crab"],
		"aisle_deli":     ["deli_turkey","deli_ham","deli_roastbeef","deli_salami","deli_bologna","deli_chiicken","deli_egg","deli_coleslaw","deli_potatosalad","deli_macaroni","deli_hummus"],
		"aisle_bakery":   ["bread_white","bread_wheat","bread_sourdough","bread_rye","bread_baguette","bread_brioche","bread_pumpernickel","bagel","croissant","muffin_blue","muffin_choc","donut_glazed","donut_choc","cake_choc","cake_vanilla","cake_cheesecake","pie_apple","pie_cherry","pastry","tortilla","naan"],
		"aisle_pantry":   ["rice_white","rice_brown","rice_basmathi","pasta_spaghetti","pasta_penne","pasta_fusilli","pasta_lasagna","pasta_ramen","flour_allpur","flour_bread","flour_almond","sugar_white","sugar_brown","sugar_powder","honey","maple_syrup","jam_strawberry","jam_grape","peanut_butter","olive_oil","cooking_oil","coconut_oil","vinegar_white","vinegar_balsamic","soy_sauce","ketchup","mustard","mayonnaise","bbq_sauce","hot_sauce","salsa","pasta_sauce_red","pasta_sauce_white","broth_beef","broth_chicken","broth_veg","soup_chicken","soup_tomato","soup_veg","soup_mushroom","beans_kidney","beans_black","beans_chickpeas","lentils","cereal_corn","cereal_oat","cereal_granola","cereal_muesli","cereal_choc","instant_oatmeal","pancake_mix","baking_powder","baking_soda","yeast","corn_starch","cocoa_powder","vanilla_extract","chicken_season","italian_season","paprika","cinnamon","garlic_salt","black_pepper","sea_salt","sugar_confectioner"],
		"aisle_frozen":   ["frozen_pizza","frozen_burger","frozen_fish","frozen_chicken","frozen_fries","frozen_corn","frozen_broccoli","frozen_mixveg","frozen_peas","icecream_vanilla","icecream_choc","icecream_straw","icecream_mint","frozen_waffles","frozen_tv_dinner","frozen_taquitos","popsicle"],
		"aisle_hbc":      ["vitamins_mult","vitamins_c","vitamins_d","vitamins_b","fish_oil","calcium","iron_supplement","pain_reliever","cough_syrup","cold_medicine","allergy_med","antacid","toothpaste","mouthwash","shampoo","conditioner","body_wash","hand_soap","deodorant","razor","bandages","sunscreen","lip_balm","hand_cream","contact_lens"],
		"aisle_household":["paper_towels","toilet_paper","tissues","dish_soap","laundry_det","fabric_softener","bleach","all_purpose_cleaner","glass_cleaner","trash_bags","aluminum_foil","plastic_wrap","ziplock_bags","sponge","light_bulb","batteries_aa","batteries_aaa","candle","insect_spray"],
		"aisle_baby":     ["diapers","baby_wipes","baby_formula","baby_food","baby_shampoo","baby_lotion","baby_oil","diaper_cream","pacifier","baby_bottle"],
	}
	var ids: Array = mapping.get(aisle_id, [])
	var result: Array = []
	for id in ids:
		if all.has(id):
			result.append(all[id])
	return result

static func get_product(id: String) -> Product:
	var all := get_all_products()
	return all.get(id)

static func get_all_categories() -> Array:
	return ["produce","dairy","beverages","snacks","meat","deli","bakery","pantry","frozen","hbc","household","baby"]
